<?php
/**
 * Raga Chatbot — Centralized Country Data (Sync with Countries.jsx)
 */

return [
    ['name' => 'Afghanistan', 'code' => '+93', 'phoneLength' => 9],
    ['name' => 'Albania', 'code' => '+355', 'phoneLength' => 9],
    ['name' => 'Algeria', 'code' => '+213', 'phoneLength' => 9],
    ['name' => 'Andorra', 'code' => '+376', 'phoneLength' => 6],
    ['name' => 'Angola', 'code' => '+244', 'phoneLength' => 9],
    ['name' => 'Antigua and Barbuda', 'code' => '+1', 'phoneLength' => 7],
    ['name' => 'Argentina', 'code' => '+54', 'phoneLength' => 10],
    ['name' => 'Armenia', 'code' => '+374', 'phoneLength' => 8],
    ['name' => 'Australia', 'code' => '+61', 'phoneLength' => 9, 'aliases' => ['AUS']],
    ['name' => 'Austria', 'code' => '+43', 'phoneLength' => 10],
    ['name' => 'Azerbaijan', 'code' => '+994', 'phoneLength' => 9],
    ['name' => 'Bahamas', 'code' => '+1', 'phoneLength' => 7],
    ['name' => 'Bahrain', 'code' => '+973', 'phoneLength' => 8],
    ['name' => 'Bangladesh', 'code' => '+880', 'phoneLength' => 10],
    ['name' => 'Barbados', 'code' => '+1', 'phoneLength' => 7],
    ['name' => 'Belarus', 'code' => '+375', 'phoneLength' => 9],
    ['name' => 'Belgium', 'code' => '+32', 'phoneLength' => 9],
    ['name' => 'Belize', 'code' => '+501', 'phoneLength' => 7],
    ['name' => 'Benin', 'code' => '+229', 'phoneLength' => 8],
    ['name' => 'Bhutan', 'code' => '+975', 'phoneLength' => 8],
    ['name' => 'Bolivia', 'code' => '+591', 'phoneLength' => 8],
    ['name' => 'Bosnia and Herzegovina', 'code' => '+387', 'phoneLength' => 8],
    ['name' => 'Botswana', 'code' => '+267', 'phoneLength' => 8],
    ['name' => 'Brazil', 'code' => '+55', 'phoneLength' => 11],
    ['name' => 'Brunei', 'code' => '+673', 'phoneLength' => 7],
    ['name' => 'Bulgaria', 'code' => '+359', 'phoneLength' => 9],
    ['name' => 'Burkina Faso', 'code' => '+226', 'phoneLength' => 8],
    ['name' => 'Burundi', 'code' => '+257', 'phoneLength' => 8],
    ['name' => 'Cambodia', 'code' => '+855', 'phoneLength' => 9],
    ['name' => 'Cameroon', 'code' => '+237', 'phoneLength' => 9],
    ['name' => 'Canada', 'code' => '+1', 'phoneLength' => 10],
    ['name' => 'Cape Verde', 'code' => '+238', 'phoneLength' => 7],
    ['name' => 'Central African Republic', 'code' => '+236', 'phoneLength' => 8],
    ['name' => 'Chad', 'code' => '+235', 'phoneLength' => 8],
    ['name' => 'Chile', 'code' => '+56', 'phoneLength' => 9],
    ['name' => 'China', 'code' => '+86', 'phoneLength' => 11],
    ['name' => 'Colombia', 'code' => '+57', 'phoneLength' => 10],
    ['name' => 'Comoros', 'code' => '+269', 'phoneLength' => 7],
    ['name' => 'Congo', 'code' => '+242', 'phoneLength' => 9],
    ['name' => 'Costa Rica', 'code' => '+506', 'phoneLength' => 8],
    ['name' => 'Croatia', 'code' => '+385', 'phoneLength' => 9],
    ['name' => 'Cuba', 'code' => '+53', 'phoneLength' => 8],
    ['name' => 'Cyprus', 'code' => '+357', 'phoneLength' => 8],
    ['name' => 'Czech Republic', 'code' => '+420', 'phoneLength' => 9],
    ['name' => 'Denmark', 'code' => '+45', 'phoneLength' => 8],
    ['name' => 'Djibouti', 'code' => '+253', 'phoneLength' => 6],
    ['name' => 'Dominica', 'code' => '+1', 'phoneLength' => 7],
    ['name' => 'Dominican Republic', 'code' => '+1', 'phoneLength' => 10],
    ['name' => 'Ecuador', 'code' => '+593', 'phoneLength' => 9],
    ['name' => 'Egypt', 'code' => '+20', 'phoneLength' => 10],
    ['name' => 'El Salvador', 'code' => '+503', 'phoneLength' => 8],
    ['name' => 'Equatorial Guinea', 'code' => '+240', 'phoneLength' => 9],
    ['name' => 'Eritrea', 'code' => '+291', 'phoneLength' => 7],
    ['name' => 'Estonia', 'code' => '+372', 'phoneLength' => 7],
    ['name' => 'Ethiopia', 'code' => '+251', 'phoneLength' => 9],
    ['name' => 'Fiji', 'code' => '+679', 'phoneLength' => 7],
    ['name' => 'Finland', 'code' => '+358', 'phoneLength' => 10],
    ['name' => 'France', 'code' => '+33', 'phoneLength' => 9],
    ['name' => 'Gabon', 'code' => '+241', 'phoneLength' => 8],
    ['name' => 'Gambia', 'code' => '+220', 'phoneLength' => 7],
    ['name' => 'Georgia', 'code' => '+995', 'phoneLength' => 9],
    ['name' => 'Germany', 'code' => '+49', 'phoneLength' => 11],
    ['name' => 'Ghana', 'code' => '+233', 'phoneLength' => 9],
    ['name' => 'Greece', 'code' => '+30', 'phoneLength' => 10],
    ['name' => 'Grenada', 'code' => '+1', 'phoneLength' => 7],
    ['name' => 'Guatemala', 'code' => '+502', 'phoneLength' => 8],
    ['name' => 'Guinea', 'code' => '+224', 'phoneLength' => 9],
    ['name' => 'Guinea-Bissau', 'code' => '+245', 'phoneLength' => 7],
    ['name' => 'Guyana', 'code' => '+592', 'phoneLength' => 7],
    ['name' => 'Haiti', 'code' => '+509', 'phoneLength' => 8],
    ['name' => 'Honduras', 'code' => '+504', 'phoneLength' => 8],
    ['name' => 'Hungary', 'code' => '+36', 'phoneLength' => 9],
    ['name' => 'Iceland', 'code' => '+354', 'phoneLength' => 7],
    ['name' => 'India', 'code' => '+91', 'phoneLength' => 10, 'aliases' => ['IND', 'Bharat', 'Hindustan']],
    ['name' => 'Indonesia', 'code' => '+62', 'phoneLength' => 11],
    ['name' => 'Iran', 'code' => '+98', 'phoneLength' => 10],
    ['name' => 'Iraq', 'code' => '+964', 'phoneLength' => 10],
    ['name' => 'Ireland', 'code' => '+353', 'phoneLength' => 9],
    ['name' => 'Israel', 'code' => '+972', 'phoneLength' => 9],
    ['name' => 'Italy', 'code' => '+39', 'phoneLength' => 10],
    ['name' => 'Jamaica', 'code' => '+1', 'phoneLength' => 7],
    ['name' => 'Japan', 'code' => '+81', 'phoneLength' => 10],
    ['name' => 'Jordan', 'code' => '+962', 'phoneLength' => 9],
    ['name' => 'Kazakhstan', 'code' => '+7', 'phoneLength' => 10],
    ['name' => 'Kenya', 'code' => '+254', 'phoneLength' => 9],
    ['name' => 'Kiribati', 'code' => '+686', 'phoneLength' => 5],
    ['name' => 'Kuwait', 'code' => '+965', 'phoneLength' => 8],
    ['name' => 'Kyrgyzstan', 'code' => '+996', 'phoneLength' => 9],
    ['name' => 'Laos', 'code' => '+856', 'phoneLength' => 8],
    ['name' => 'Latvia', 'code' => '+371', 'phoneLength' => 8],
    ['name' => 'Lebanon', 'code' => '+961', 'phoneLength' => 8],
    ['name' => 'Lesotho', 'code' => '+266', 'phoneLength' => 8],
    ['name' => 'Liberia', 'code' => '+231', 'phoneLength' => 7],
    ['name' => 'Libya', 'code' => '+218', 'phoneLength' => 9],
    ['name' => 'Liechtenstein', 'code' => '+423', 'phoneLength' => 7],
    ['name' => 'Lithuania', 'code' => '+370', 'phoneLength' => 8],
    ['name' => 'Luxembourg', 'code' => '+352', 'phoneLength' => 9],
    ['name' => 'Macedonia', 'code' => '+389', 'phoneLength' => 8],
    ['name' => 'Madagascar', 'code' => '+261', 'phoneLength' => 9],
    ['name' => 'Malawi', 'code' => '+265', 'phoneLength' => 9],
    ['name' => 'Malaysia', 'code' => '+60', 'phoneLength' => 9],
    ['name' => 'Maldives', 'code' => '+960', 'phoneLength' => 7],
    ['name' => 'Mali', 'code' => '+223', 'phoneLength' => 8],
    ['name' => 'Malta', 'code' => '+356', 'phoneLength' => 8],
    ['name' => 'Marshall Islands', 'code' => '+692', 'phoneLength' => 7],
    ['name' => 'Mauritania', 'code' => '+222', 'phoneLength' => 8],
    ['name' => 'Mauritius', 'code' => '+230', 'phoneLength' => 8],
    ['name' => 'Mexico', 'code' => '+52', 'phoneLength' => 10],
    ['name' => 'Micronesia', 'code' => '+691', 'phoneLength' => 7],
    ['name' => 'Moldova', 'code' => '+373', 'phoneLength' => 8],
    ['name' => 'Monaco', 'code' => '+377', 'phoneLength' => 8],
    ['name' => 'Mongolia', 'code' => '+976', 'phoneLength' => 8],
    ['name' => 'Montenegro', 'code' => '+382', 'phoneLength' => 8],
    ['name' => 'Morocco', 'code' => '+212', 'phoneLength' => 9],
    ['name' => 'Mozambique', 'code' => '+258', 'phoneLength' => 9],
    ['name' => 'Myanmar', 'code' => '+95', 'phoneLength' => 9],
    ['name' => 'Namibia', 'code' => '+264', 'phoneLength' => 9],
    ['name' => 'Nauru', 'code' => '+674', 'phoneLength' => 7],
    ['name' => 'Nepal', 'code' => '+977', 'phoneLength' => 10],
    ['name' => 'Netherlands', 'code' => '+31', 'phoneLength' => 9],
    ['name' => 'New Zealand', 'code' => '+64', 'phoneLength' => 9],
    ['name' => 'Nicaragua', 'code' => '+505', 'phoneLength' => 8],
    ['name' => 'Niger', 'code' => '+227', 'phoneLength' => 8],
    ['name' => 'Nigeria', 'code' => '+234', 'phoneLength' => 10],
    ['name' => 'North Korea', 'code' => '+850', 'phoneLength' => 10],
    ['name' => 'Norway', 'code' => '+47', 'phoneLength' => 8],
    ['name' => 'Oman', 'code' => '+968', 'phoneLength' => 8],
    ['name' => 'Pakistan', 'code' => '+92', 'phoneLength' => 10],
    ['name' => 'Palau', 'code' => '+680', 'phoneLength' => 7],
    ['name' => 'Panama', 'code' => '+507', 'phoneLength' => 8],
    ['name' => 'Papua New Guinea', 'code' => '+675', 'phoneLength' => 8],
    ['name' => 'Paraguay', 'code' => '+595', 'phoneLength' => 9],
    ['name' => 'Peru', 'code' => '+51', 'phoneLength' => 9],
    ['name' => 'Philippines', 'code' => '+63', 'phoneLength' => 10],
    ['name' => 'Poland', 'code' => '+48', 'phoneLength' => 9],
    ['name' => 'Portugal', 'code' => '+351', 'phoneLength' => 9],
    ['name' => 'Qatar', 'code' => '+974', 'phoneLength' => 8],
    ['name' => 'Romania', 'code' => '+40', 'phoneLength' => 9],
    ['name' => 'Russia', 'code' => '+7', 'phoneLength' => 10],
    ['name' => 'Rwanda', 'code' => '+250', 'phoneLength' => 9],
    ['name' => 'Saint Kitts and Nevis', 'code' => '+1', 'phoneLength' => 7],
    ['name' => 'Saint Lucia', 'code' => '+1', 'phoneLength' => 7],
    ['name' => 'Saint Vincent', 'code' => '+1', 'phoneLength' => 7],
    ['name' => 'Samoa', 'code' => '+685', 'phoneLength' => 7],
    ['name' => 'San Marino', 'code' => '+378', 'phoneLength' => 10],
    ['name' => 'Sao Tome and Principe', 'code' => '+239', 'phoneLength' => 7],
    ['name' => 'Saudi Arabia', 'code' => '+966', 'phoneLength' => 9],
    ['name' => 'Senegal', 'code' => '+221', 'phoneLength' => 9],
    ['name' => 'Serbia', 'code' => '+381', 'phoneLength' => 9],
    ['name' => 'Seychelles', 'code' => '+248', 'phoneLength' => 7],
    ['name' => 'Sierra Leone', 'code' => '+232', 'phoneLength' => 8],
    ['name' => 'Singapore', 'code' => '+65', 'phoneLength' => 8],
    ['name' => 'Slovakia', 'code' => '+421', 'phoneLength' => 9],
    ['name' => 'Slovenia', 'code' => '+386', 'phoneLength' => 8],
    ['name' => 'Solomon Islands', 'code' => '+677', 'phoneLength' => 7],
    ['name' => 'Somalia', 'code' => '+252', 'phoneLength' => 8],
    ['name' => 'South Africa', 'code' => '+27', 'phoneLength' => 9],
    ['name' => 'South Korea', 'code' => '+82', 'phoneLength' => 10],
    ['name' => 'South Sudan', 'code' => '+211', 'phoneLength' => 9],
    ['name' => 'Spain', 'code' => '+34', 'phoneLength' => 9],
    ['name' => 'Sri Lanka', 'code' => '+94', 'phoneLength' => 9],
    ['name' => 'Sudan', 'code' => '+249', 'phoneLength' => 9],
    ['name' => 'Suriname', 'code' => '+597', 'phoneLength' => 7],
    ['name' => 'Swaziland', 'code' => '+268', 'phoneLength' => 7],
    ['name' => 'Sweden', 'code' => '+46', 'phoneLength' => 9],
    ['name' => 'Switzerland', 'code' => '+41', 'phoneLength' => 9],
    ['name' => 'Syria', 'code' => '+963', 'phoneLength' => 9],
    ['name' => 'Taiwan', 'code' => '+886', 'phoneLength' => 9],
    ['name' => 'Tajikistan', 'code' => '+992', 'phoneLength' => 9],
    ['name' => 'Tanzania', 'code' => '+255', 'phoneLength' => 9],
    ['name' => 'Thailand', 'code' => '+66', 'phoneLength' => 9],
    ['name' => 'Timor-Leste', 'code' => '+670', 'phoneLength' => 7],
    ['name' => 'Togo', 'code' => '+228', 'phoneLength' => 8],
    ['name' => 'Tonga', 'code' => '+676', 'phoneLength' => 7],
    ['name' => 'Trinidad and Tobago', 'code' => '+1', 'phoneLength' => 7],
    ['name' => 'Tunisia', 'code' => '+216', 'phoneLength' => 8],
    ['name' => 'Turkey', 'code' => '+90', 'phoneLength' => 10],
    ['name' => 'Turkmenistan', 'code' => '+993', 'phoneLength' => 8],
    ['name' => 'Tuvalu', 'code' => '+688', 'phoneLength' => 5],
    ['name' => 'Uganda', 'code' => '+256', 'phoneLength' => 9],
    ['name' => 'Ukraine', 'code' => '+380', 'phoneLength' => 9],
    ['name' => 'United Arab Emirates', 'code' => '+971', 'phoneLength' => 9, 'aliases' => ['UAE', 'Emirates', 'Dubai', 'Abu Dhabi']],
    ['name' => 'United Kingdom', 'code' => '+44', 'phoneLength' => 10, 'aliases' => ['UK', 'Britain', 'England', 'Scotland', 'Wales']],
    ['name' => 'United States', 'code' => '+1', 'phoneLength' => 10, 'aliases' => ['USA', 'US', 'America']],
    ['name' => 'Uruguay', 'code' => '+598', 'phoneLength' => 8],
    ['name' => 'Uzbekistan', 'code' => '+998', 'phoneLength' => 9],
    ['name' => 'Vanuatu', 'code' => '+678', 'phoneLength' => 7],
    ['name' => 'Vatican City', 'code' => '+379', 'phoneLength' => 10],
    ['name' => 'Venezuela', 'code' => '+58', 'phoneLength' => 10],
    ['name' => 'Vietnam', 'code' => '+84', 'phoneLength' => 9],
    ['name' => 'Yemen', 'code' => '+967', 'phoneLength' => 9],
    ['name' => 'Zambia', 'code' => '+260', 'phoneLength' => 9],
    ['name' => 'Zimbabwe', 'code' => '+263', 'phoneLength' => 9]
];
